import type { DependencyAnalysis } from '../analyzers/index.js';

/**
 * Generate a mermaid dependency diagram from analysis results.
 */
export function generateMermaidDiagram(analysis: DependencyAnalysis): string {
  const lines: string[] = [];

  lines.push('```mermaid');
  lines.push('graph TD');

  // Define nodes with stability coloring via classes
  for (const mod of analysis.stability) {
    if (mod.moduleName === '_root') continue;
    const label = `${mod.moduleName}<br/><small>I=${mod.instability.toFixed(2)}</small>`;
    lines.push(`  ${sanitize(mod.moduleName)}["${label}"]`);
  }

  // Define edges
  for (const edge of analysis.edges) {
    if (edge.from === '_root' || edge.to === '_root') continue;
    const label = edge.files.length > 1 ? `${edge.files.length} imports` : '1 import';
    lines.push(`  ${sanitize(edge.from)} -->|${label}| ${sanitize(edge.to)}`);
  }

  // Style classes based on stability
  const stable: string[] = [];
  const moderate: string[] = [];
  const unstable: string[] = [];

  for (const mod of analysis.stability) {
    if (mod.moduleName === '_root') continue;
    if (mod.instability <= 0.3) stable.push(sanitize(mod.moduleName));
    else if (mod.instability <= 0.6) moderate.push(sanitize(mod.moduleName));
    else unstable.push(sanitize(mod.moduleName));
  }

  if (stable.length > 0) {
    lines.push(`  classDef stable fill:#dcfce7,stroke:#16a34a,color:#000`);
    lines.push(`  class ${stable.join(',')} stable`);
  }
  if (moderate.length > 0) {
    lines.push(`  classDef moderate fill:#fef9c3,stroke:#ca8a04,color:#000`);
    lines.push(`  class ${moderate.join(',')} moderate`);
  }
  if (unstable.length > 0) {
    lines.push(`  classDef unstable fill:#fecaca,stroke:#dc2626,color:#000`);
    lines.push(`  class ${unstable.join(',')} unstable`);
  }

  lines.push('```');

  return lines.join('\n');
}

/**
 * Generate full architecture.md content.
 */
export function generateArchitectureMd(analysis: DependencyAnalysis): string {
  const sections: string[] = [];

  sections.push('# Architecture — Dependency Map');
  sections.push('');
  sections.push('> Auto-generated by [goodbot](https://github.com/timeritual/goodbot-ai). Do not edit manually.');
  sections.push('');
  sections.push('## Module Dependency Graph');
  sections.push('');
  sections.push('Modules are colored by stability: ' +
    '**green** = stable (low instability), ' +
    '**yellow** = moderate, ' +
    '**red** = unstable (high instability).');
  sections.push('');
  sections.push(generateMermaidDiagram(analysis));
  sections.push('');

  // Stability table
  sections.push('## Stability Metrics');
  sections.push('');
  sections.push('| Module | Afferent (Ca) | Efferent (Ce) | Instability (I) |');
  sections.push('|--------|:---:|:---:|:---:|');
  for (const m of analysis.stability) {
    if (m.moduleName === '_root') continue;
    sections.push(`| ${m.moduleName} | ${m.afferentCoupling} | ${m.efferentCoupling} | ${m.instability.toFixed(2)} |`);
  }
  sections.push('');

  // Issues
  if (analysis.circularDependencies.length > 0) {
    sections.push('## Circular Dependencies');
    sections.push('');
    for (const cd of analysis.circularDependencies) {
      sections.push(`- ${cd.cycle.join(' → ')}`);
    }
    sections.push('');
  }

  if (analysis.layerViolations.length > 0) {
    sections.push('## Layer Violations');
    sections.push('');
    for (const lv of analysis.layerViolations) {
      sections.push(`- \`${lv.file}:${lv.line}\` — ${lv.fromModule} (L${lv.fromLevel}) imports from ${lv.toModule} (L${lv.toLevel})`);
    }
    sections.push('');
  }

  sections.push('---');
  sections.push('*Generated by [goodbot](https://github.com/timeritual/goodbot-ai)*');
  sections.push('');

  return sections.join('\n');
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '_');
}
