import { Command } from 'commander';
import path from 'node:path';
import ora from 'ora';
import chalk from 'chalk';
import { loadConfig, loadChecksums, saveChecksums } from '../config/index.js';
import { generateAll, buildContext } from '../generators/index.js';
import { runFullScan } from '../scanners/index.js';
import { runFullAnalysis, analyzeGitHistory, findTemporalCoupling } from '../analyzers/index.js';
import type { FullAnalysis, GitHistoryAnalysis, TemporalCoupling } from '../analyzers/index.js';
import { buildSnapshot, saveSnapshot, loadSnapshot } from '../freshness/index.js';
import { log, safeWriteFile, safeReadFile, contentHash, fileExists } from '../utils/index.js';

const GOODBOT_START = '<!-- goodbot:start -->';
const GOODBOT_END = '<!-- goodbot:end -->';

function mergeGoodbotContent(generated: string, existing: string): string {
  const startIdx = existing.indexOf(GOODBOT_START);
  const endIdx = existing.indexOf(GOODBOT_END);

  if (startIdx !== -1 && endIdx !== -1) {
    const before = existing.substring(0, startIdx);
    const after = existing.substring(endIdx + GOODBOT_END.length);
    return `${before}${GOODBOT_START}\n${generated}\n${GOODBOT_END}${after}`;
  }

  return `${GOODBOT_START}\n${generated}\n${GOODBOT_END}\n\n${existing}`;
}

export const generateCommand = new Command('generate')
  .description('Generate AI agent guardrail files from your config')
  .option('-p, --path <path>', 'Project path', process.cwd())
  .option('--force', 'Overwrite existing files without prompting', false)
  .option('--dry-run', 'Show what would be generated without writing', false)
  .option('--analyze', 'Run analysis first and generate adaptive guardrails based on findings', false)
  .action(async (opts) => {
    const projectRoot = opts.path;

    let config;
    try {
      config = await loadConfig(projectRoot);
    } catch (err) {
      log.error(err instanceof Error ? err.message : String(err));
      process.exit(1);
    }

    let fullAnalysis: FullAnalysis | undefined;
    let gitHistory: GitHistoryAnalysis | undefined;
    let temporalCouplings: TemporalCoupling[] | undefined;

    // Always scan for framework patterns
    const scanSpinner = ora('Scanning project...').start();
    const scan = await runFullScan(projectRoot);
    scanSpinner.succeed('Scan complete');

    // Auto-analyze on first run (no existing snapshot)
    let shouldAnalyze = opts.analyze;
    if (!shouldAnalyze) {
      const existingSnapshot = await loadSnapshot(projectRoot);
      if (!existingSnapshot) {
        shouldAnalyze = true;
        log.info('First run detected — running analysis automatically.');
      } else {
        log.dim('Skipping analysis (snapshot exists). Use --analyze to refresh.');
      }
    }

    if (shouldAnalyze) {
      const analyzeSpinner = ora('Analyzing project for adaptive guardrails...').start();
      try {
        fullAnalysis = await runFullAnalysis(projectRoot, scan.structure, config);
        analyzeSpinner.text = 'Analyzing git history...';
        gitHistory = await analyzeGitHistory(projectRoot, 500, scan.structure.srcRoot ?? undefined);
        temporalCouplings = findTemporalCoupling(gitHistory.commits, 3, 0.5, scan.structure.srcRoot ?? undefined);
        const aiPct = Math.round(gitHistory.aiCommitRatio * 100);
        analyzeSpinner.succeed(
          `Analysis complete — ${fullAnalysis.health.grade} (${fullAnalysis.health.score}/100), ${gitHistory.totalCommits} commits (${aiPct}% AI)`,
        );
        if (fullAnalysis.health.contributors.length > 0) {
          log.dim('  Biggest issues:');
          for (const c of fullAnalysis.health.contributors.slice(0, 5)) {
            log.dim(`    ${String(c.count).padStart(4)}  ${c.label}`);
          }
        }
      } catch (err) {
        analyzeSpinner.warn('Analysis failed — generating without analysis data');
        log.dim(`  ${err instanceof Error ? err.message : String(err)}`);
      }
    }

    const spinner = ora('Generating files...').start();

    try {
      const files = await generateAll(config, fullAnalysis, gitHistory, temporalCouplings, scan.frameworkPatterns);
      spinner.succeed(`Generated ${files.length} files`);

      const existingChecksums = await loadChecksums(projectRoot);
      const checksums: Record<string, string> = {};

      for (const file of files) {
        const filePath = path.join(projectRoot, file.relativePath);
        const existing = await safeReadFile(filePath);

        // Determine if this existing file was previously generated by goodbot
        const previouslyGenerated = existing !== null && (
          existingChecksums[file.relativePath] !== undefined ||
          existing.includes(GOODBOT_START)
        );

        // Respect config strategy for existing files not previously generated
        const strategy = config.agentFiles.existingFileStrategy ?? 'merge';
        const isUserFile = file.mergeWithExisting && existing !== null && !previouslyGenerated;

        // Skip: don't touch pre-existing user files
        if (isUserFile && strategy === 'skip') {
          if (opts.dryRun) {
            log.dim(`  ${file.fileName} ${chalk.dim('(would skip — existing file)')}`);
          } else {
            log.dim(`  ${file.fileName} — skipped (existing file)`);
          }
          continue;
        }

        // Merge: prepend goodbot content to pre-existing user files
        const shouldMerge = isUserFile && strategy === 'merge';
        const finalContent = shouldMerge
          ? mergeGoodbotContent(file.content, existing)
          : file.content;

        if (opts.dryRun) {
          if (shouldMerge) {
            log.warn(`${file.fileName} ${chalk.dim('(would prepend goodbot section)')}`);
          } else if (existing) {
            log.warn(`${file.fileName} ${chalk.dim('(would overwrite)')}`);
          } else {
            log.success(`${file.fileName} ${chalk.dim('(would create)')}`);
          }
          continue;
        }

        if (existing && !opts.force) {
          if (existing === finalContent) {
            log.dim(`  ${file.fileName} — no changes`);
            checksums[file.relativePath] = contentHash(finalContent);
            continue;
          }
          if (shouldMerge) {
            log.info(`${file.fileName} — prepending goodbot section (your content preserved below)`);
          } else {
            log.warn(`${file.fileName} — overwriting (use --dry-run to preview)`);
          }
        }

        await safeWriteFile(filePath, finalContent);
        checksums[file.relativePath] = contentHash(finalContent);
        log.success(`${file.fileName}`);
      }

      if (!opts.dryRun) {
        await saveChecksums(projectRoot, checksums);

        // Save analysis snapshot for freshness tracking
        if (fullAnalysis) {
          const context = buildContext(config, undefined, fullAnalysis, gitHistory, temporalCouplings);
          if (context.analysisInsights) {
            const snapshot = buildSnapshot(
              context.analysisInsights,
              config.conventions.customRules,
              fullAnalysis.dependency.modules.length,
              fullAnalysis.dependency.filesParsed,
            );
            await saveSnapshot(projectRoot, snapshot);
            log.dim('Snapshot saved for freshness tracking.');
          }
        }

        // Ensure .goodbot/.gitignore exists
        const gitignorePath = path.join(projectRoot, '.goodbot', '.gitignore');
        if (!(await fileExists(gitignorePath))) {
          await safeWriteFile(gitignorePath, `# Generated by goodbot — local analysis state, not shared\nsnapshot.json\nchecksums.json\nhistory.json\n`);
        }

        console.log();
        log.dim('Run `goodbot check` to verify files stay in sync.');
      }
    } catch (err) {
      spinner.fail('Generation failed');
      log.error(err instanceof Error ? err.message : String(err));
      process.exit(1);
    }
  });
