import { describe, it, expect } from 'vitest';
import { classifyCommit, type GitCommit } from './git-history.js';

function makeCommit(overrides: Partial<GitCommit> = {}): GitCommit {
  return {
    hash: 'abc123',
    authorEmail: 'dev@example.com',
    date: '2026-01-01 12:00:00 -0500',
    subject: 'Update feature',
    body: '',
    isAI: false,
    files: [],
    ...overrides,
  };
}

describe('classifyCommit', () => {
  it('detects Co-Authored-By Claude', () => {
    const commit = makeCommit({
      body: 'Some change\n\nCo-Authored-By: Claude <noreply@anthropic.com>',
    });
    expect(classifyCommit(commit)).toBe(true);
  });

  it('detects Co-Authored-By Copilot', () => {
    const commit = makeCommit({
      body: 'Co-Authored-By: Copilot <copilot@github.com>',
    });
    expect(classifyCommit(commit)).toBe(true);
  });

  it('detects "Generated with Claude Code" in subject', () => {
    const commit = makeCommit({
      subject: 'Generated with Claude Code',
    });
    expect(classifyCommit(commit)).toBe(true);
  });

  it('detects "Generated by Cursor" in body', () => {
    const commit = makeCommit({
      body: 'Generated by Cursor AI',
    });
    expect(classifyCommit(commit)).toBe(true);
  });

  it('detects emoji-prefixed generated markers', () => {
    const commit = makeCommit({
      body: '🤖 Generated with Claude Code',
    });
    expect(classifyCommit(commit)).toBe(true);
  });

  it('detects bot email addresses', () => {
    const commit = makeCommit({
      authorEmail: 'github-actions[bot]@users.noreply.github.com',
    });
    expect(classifyCommit(commit)).toBe(true);
  });

  it('detects dependabot', () => {
    const commit = makeCommit({
      authorEmail: 'dependabot[bot]@users.noreply.github.com',
    });
    expect(classifyCommit(commit)).toBe(true);
  });

  it('does not flag normal human commits', () => {
    const commit = makeCommit({
      subject: 'Fix login bug',
      body: 'Updated the auth middleware to handle edge case',
      authorEmail: 'developer@company.com',
    });
    expect(classifyCommit(commit)).toBe(false);
  });

  it('does not flag commits that mention AI in content but are not AI-authored', () => {
    const commit = makeCommit({
      subject: 'Add AI model configuration',
      body: 'Set up the Claude API client',
    });
    expect(classifyCommit(commit)).toBe(false);
  });

  it('detects noreply@anthropic.com author email', () => {
    const commit = makeCommit({
      authorEmail: 'noreply@anthropic.com',
    });
    expect(classifyCommit(commit)).toBe(true);
  });
});
